version: '3.8'

services:

  mysql-patient:
    image: mysql:8.0
    container_name: mysql-patient
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_portal_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-patient-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-patient-data: